-- MySQL Script generated by MySQL Workbench
-- Wed Oct 25 11:20:20 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Usuarios` (
  `IdUsuario` INT NOT NULL AUTO_INCREMENT,
  `Nombres` VARCHAR(45) NOT NULL,
  `Apellidos` VARCHAR(45) NOT NULL,
  `Identificacion` INT NOT NULL,
  `Correo` VARCHAR(45) NOT NULL,
  `passwd` VARCHAR(45) NOT NULL,
  `nickname` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`IdUsuario`),
  UNIQUE INDEX `IdUsuario_UNIQUE` (`IdUsuario` ASC) VISIBLE,
  UNIQUE INDEX `Identificacion_UNIQUE` (`Identificacion` ASC) VISIBLE,
  UNIQUE INDEX `Correo_UNIQUE` (`Correo` ASC) VISIBLE,
  UNIQUE INDEX `nickname_UNIQUE` (`nickname` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Grupos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Grupos` (
  `IdGrupos` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(45) NOT NULL,
  `Usuarios_IdUsuario` INT NOT NULL,
  PRIMARY KEY (`IdGrupos`, `Usuarios_IdUsuario`),
  UNIQUE INDEX `IdGrupos_UNIQUE` (`IdGrupos` ASC) VISIBLE,
  INDEX `fk_Grupos_Usuarios1_idx` (`Usuarios_IdUsuario` ASC) VISIBLE,
  CONSTRAINT `fk_Grupos_Usuarios1`
    FOREIGN KEY (`Usuarios_IdUsuario`)
    REFERENCES `mydb`.`Usuarios` (`IdUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Publicaciones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Publicaciones` (
  `idPublicaciones` INT NOT NULL AUTO_INCREMENT,
  `Titulo` VARCHAR(45) NULL DEFAULT NULL,
  `Descripcion` VARCHAR(45) NULL DEFAULT NULL,
  `Video` VARCHAR(45) NULL DEFAULT NULL,
  `Imagen` VARCHAR(45) NULL DEFAULT NULL,
  `Grupos_IdGrupos` INT NOT NULL,
  PRIMARY KEY (`idPublicaciones`, `Grupos_IdGrupos`),
  UNIQUE INDEX `idPublicaciones_UNIQUE` (`idPublicaciones` ASC) VISIBLE,
  INDEX `fk_Publicaciones_Grupos1_idx` (`Grupos_IdGrupos` ASC) VISIBLE,
  CONSTRAINT `fk_Publicaciones_Grupos1`
    FOREIGN KEY (`Grupos_IdGrupos`)
    REFERENCES `mydb`.`Grupos` (`IdGrupos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
